ARDUINO_DIR = /usr/share/arduino
ARDUINO_PORT = /dev/ttyACM*

ARDUINO_LIBS = Robot Parser PWM DynamixelSerial2 LiquidCrystal Wire SPI Adafruit_BNO055 Adafruit_Sensor
USER_LIB_PATH = /home/pi/2k19/libraries
BOARD_TAG = mega2560

include /usr/share/arduino/Arduino.mk
